const CATALOG = [
    {
        id: 'el1',
        category_mus: 'guitar',
        category_man: 'dimebag-darrell',
        name: '1981 Dean ML - "The Dean from Hell"',
        img: 'img/man-dimebag-darrell/1981-dean-from-hell-xl.png',
        price: 50000,
        story: 'В интервью 1994 года Даймбэг Даррелл называет свою гитару 1981 года синюю Dean from Hell своей рабочей лошадкой. "Я придерживался того, что всегда использовал, - усилителей Randall, а моим основным инструментом по-прежнему остается моя синяя гитара 81-го года с наклейками Kiss. Эту гитару просто невозможно остановить. Я использую ее во всех песнях, которые находятся в стандартном строю", - сказал он.',
        more: '<a href="https://www.guitarworld.com/gw-archive/dimebag-darrell-discusses-his-roots-gear-and-pantera-1994-guitar-world-interview">Ссылка на источник</a>',
    },
    {
        id: 'el2',
        category_mus: 'guitar',
        category_man: 'dimebag-darrell',
        name: 'Dean Dimebag Concrete Sledge ML - Reversed Headstock',
        img: 'img/man-dimebag-darrell/dean-dimebag-concrete-sledge-ml-reversed-headstock-xl.png',
        price: 60000,
        story: 'Даймбэг Даррелл использовал эту гитару в 1990 году на концерте в Москве во время "Primal Concrete Sledge"',
        more: '<iframe src="https://www.youtube.com/embed/3DOamgay6Mw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el3',
        category_mus: 'accessory',
        category_man: 'dimebag-darrell',
        name: 'Dunlop Tortex Standard 0.88mm Guitar Picks (50шт.)',
        img: 'img/man-dimebag-darrell/dunlop-tortex-standard-0-88mm-guitar-picks-xl.png',
        price: 2000,
        story: 'Даймбэг Даррелл использовал эти медиаторы на протяжении всей игры в Pantera',
        more: 'Пост в инстаграме Рекса Брауна <br> <img src="img/man-dimebag-darrell/dime_pick.jpg" alt="">',
    },
    {
        id: 'el4',
        category_mus: 'pedal',
        category_man: 'dimebag-darrell',
        name: 'MXR 6-Band Graphic Equalizer',
        img: 'img/man-dimebag-darrell/mxr-6-band-graphic-equalizer-xl.png',
        price: 8000,
        story: 'В интервью Guitar World после выхода "Vulgar Display of Power", когда Даймбэга Даррелла спросили о его педалях эффектов, он ответил: "На самом деле это довольно просто. Я подключаю свою гитару к шестиполосному эквалайзеру Furman PQ-4, MXR Blue, к моему шумоподавителю Rocktron Hush 2-B и к усилителям. И на этом все."',
        more: '<a href="https://www.guitarworld.com/gw-archive/dimebag-darrell-discusses-his-roots-gear-and-pantera-1994-guitar-world-interview">Ссылка на источник</a>',
    },
    {
        id: 'el5',
        category_mus: 'amp',
        category_man: 'dimebag-darrell',
        name: 'Randall Warhead 2CH 300 Watt Amp Head',
        img: 'img/man-dimebag-darrell/randall-warhead-2ch-300-watt-amp-head-xl.png',
        price: 12000,
        story: 'На скриншоте клипа Pantera - Revolution Is My Name можно увидеть Randall Warhead 2CH 300 Watt Amp Head',
        more: '<img src="img/man-dimebag-darrell/dime_head.jpg" alt="">',
    },
    {
        id: 'el6',
        category_mus: 'amp',
        category_man: 'layne-staley',
        name: 'Crate AMP',
        img: 'img/man-layne-staley/crate-amp-xl.png',
        price: 12000,
        story: 'На 12:16 Лейн говорит, что у него дома есть гитарный усилитель Crate, а также множество других усилителей и эффектов.',
        more: '<iframe src="https://www.youtube.com/embed/YdbVizQqMts" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el7',
        category_mus: 'pedal',
        category_man: 'layne-staley',
        name: 'Dunlop Cry Baby Wah Pedal',
        img: 'img/man-layne-staley/dunlop-cry-baby-wah-pedal-xl.png',
        price: 10000,
        story: 'На 12:33 Лейн говорит, что использует педаль wah-wah.',
        more: '<iframe src="https://www.youtube.com/embed/YdbVizQqMts" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el8',
        category_mus: 'guitar',
        category_man: 'layne-staley',
        name: 'Gibson Hummingbird',
        img: 'img/man-layne-staley/gibson-hummingbird-xl.png',
        price: 35000,
        story: 'На протяжении всего видео Лейн на акустической гитаре Gibson. Это единственный раз, когда его можно увидеть с этой гитарой (выступление MTV Unplugged 1996 года, один из последних раз, когда группа играла вместе с Лейном)',
        more: '<iframe src="https://www.youtube.com/embed/FSlcR2Fnk_o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el9',
        category_mus: 'guitar',
        category_man: 'layne-staley',
        name: 'Gibson SG Standard Electric Guitar',
        img: 'img/man-layne-staley/gibson-sg-standard-electric-guitar-xl.png',
        price: 30000,
        story: 'В видео, снятом 31 декабря 1992 года для MTV "Drop the Ball New Years eve Party", можно увидеть, как Лейн играет на гитаре Gibson SG на 2:17.',
        more: '<iframe src="https://www.youtube.com/embed/uZ3GDusXV_A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el10',
        category_mus: 'studio',
        category_man: 'layne-staley',
        name: 'Maestro PS-1A Phase Shifter',
        img: 'img/man-layne-staley/maestro-ps-1a-phase-shifter-xl.png',
        price: 13000,
        story: 'На 12:16 Лейн начинает называть все оборудование, которое у него есть дома. Примерно через 4 или 5 секунд он говорит, что у него дома есть Flanger, а также Phase Shifter.',
        more: '<iframe src="https://www.youtube.com/embed/YdbVizQqMts" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el11',
        category_mus: 'accessory',
        category_man: 'jerry-cantrell',
        name: 'Dunlop Tortex Standard 1.0mm Guitar Picks (50 шт.)',
        img: 'img/man-jerry-cantrell/dunlop-tortex-standard-1-0mm-guitar-picks-xl.png',
        price: 2000,
        story: 'Согласно этой рекламе Dunlop, Джерри Кантрелл из Alice in Chains использует 1.0-миллиметровые медиаторы Dunlop Tortex.',
        more: '<img src="img/man-jerry-cantrell/jerry_pick.jpg" alt="">',
    },
    {
        id: 'el12',
        category_mus: 'guitar',
        category_man: 'jerry-cantrell',
        name: 'G&L Tribute Rampage Black',
        img: 'img/man-jerry-cantrell/g-l-tribute-rampage-black-xl.png',
        price: 65000,
        story: 'G&L Tribute Rampage - это фирменная модель гитары Джерри Кантрелла.',
        more: '<img src="img/man-jerry-cantrell/jerry_guitar.jpg" alt="">',
    },
    {
        id: 'el13',
        category_mus: 'guitar',
        category_man: 'jerry-cantrell',
        name: 'G&L Tribute Rampage Ivory',
        img: 'img/man-jerry-cantrell/g-l-tribute-rampage-ivory-xl.png',
        price: 70000,
        story: 'Основной гитарой Джерри Кантрелла является G&L Rampage. ”Они всегда казались мне действительно подходящими", - говорит Кантрелл на 2:35. “Вы знаете, эта гитароа основана на чем-то вроде модели Эдди Ван Халена, с более широким и плоским грифом, с одним звукоснимателем и одной ручкой регулировки громкости',
        more: '<iframe src="https://www.youtube.com/embed/tlqyz02I25I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el14',
        category_mus: 'pedal',
        category_man: 'jerry-cantrell',
        name: 'Ibanez TS9 Tube Screamer',
        img: 'img/man-jerry-cantrell/ibanez-ts9-tube-screamer-xl.png',
        price: 7000,
        story: 'В видео от Джерри Кантрелла видно, как сверху на Jet City JCA20H установлен Ibanez TS9 Tube Screamer.',
        more: '<iframe src="https://www.youtube.com/embed/E5DWj2NOieg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el15',
        category_mus: 'amp',
        category_man: 'jerry-cantrell',
        name: 'Marshall JCM800 2203 100W Tube Head Amp',
        img: 'img/man-jerry-cantrell/marshall-jcm800-2203-vintage-100w-tube-head-amp-xl.png',
        price: 15000,
        story: 'Использовался на первых двух альбомах Alice in Chains, Facelift (1990) и Dirt (1992). Усилитель был модифицирован Рейнхольдом Богнером, который позже работал в тесном сотрудничестве с Джерри над большинством его усилителей.',
        more: '<a href="https://www.groundguitar.com/jerry-cantrell-gear/">Ссылка на источник</a>',
    },
    {
        id: 'el16',
        category_mus: 'pedal',
        category_man: 'kurt-cobain',
        name: 'Boss DS-2 Turbo Distortion',
        img: 'img/man-kurt-cobain/boss-ds-2-turbo-distortion-xl.png',
        price: 8500,
        story: 'Курт заменил DS-1 на DS-2 примерно в 1992 году. Курт по-прежнему использовал те же настройки, что и на DS-1. Его можно увидеть в шоу Unplugged, Live at Reading и нескольких других шоу, обычно перед его Small Clone.',
        more: '<img src="img/man-kurt-cobain/kurt_pedal.jpg" alt="">',
    },
    {
        id: 'el17',
        category_mus: 'guitar',
        category_man: 'kurt-cobain',
        name: 'Fender Japan Standard Stratocaster Left Handed - Sunburst',
        img: 'img/man-kurt-cobain/fender-usa-left-standard-stratocaster-sunburst-xl.png',
        price: 45000,
        story: 'Курт Кобейн использовал этот Fender Japan Standard Stratocaster Left Handed - Sunburst на концерте в рединге в 1992 году, и он добавил звукосниматель Seymour Duncan Hot Rails',
        more: '<img src="img/man-kurt-cobain/kurt_guitar.jpg" alt="">',
    },
    {
        id: 'el18',
        category_mus: 'guitar',
        category_man: 'kurt-cobain',
        name: 'Martin D-18E Acoustic-Electric Guitar',
        img: 'img/man-kurt-cobain/martin-d-18e-acoustic-electric-guitar-xl.png',
        price: 80000,
        story: 'Кобейн использовал акустическую гитару C.F. Martin & Company D-18E во время определяющего карьеру выступления Nirvana на MTV Unplugged Live, на фотографии с выступления можно увидеть Кобейна с ней. Эта информация первоначально взята с официального веб-сайта Мартина.',
        more: '<img src="img/man-kurt-cobain/kurt_guitar2.jpg" alt="">',
    },
    {
        id: 'el19',
        category_mus: 'accessory',
        category_man: 'kurt-cobain',
        name: 'Seymour Duncan SH-4/TB-4 JB Model',
        img: 'img/man-kurt-cobain/seymour-duncan-sh-4-jb-humbucker-xl.png',
        price: 5500,
        story: 'Похоже, что Курт иногда использовал звукосниматели Seymour Duncan Hot Rails, которые представляют собой хамбакеры, но уменьшенные до размера одного звукоснимателя, что означает, что их можно было установить на его гитару практически без необратимых повреждений. В гитарах, которые могли бы им подойти, он часто использовал звукосниматели Seymour Duncan JB.',
        more: '<a href="https://www.quora.com/What-modifications-did-Kurt-Cobain-make-to-his-Guitar-Did-the-band-make-any-specific-changes-tweaks-to-their-instruments-to-produce-the-unique-guitar-sound-in-many-of-their-songs-If-yes-what-are-they">Ссылка на источник</a>',
    },
    {
        id: 'el20',
        category_mus: 'amp',
        category_man: 'kurt-cobain',
        name: 'Vox AC30 Guitar Combo Amp',
        img: 'img/man-kurt-cobain/vox-ac30-guitar-combo-amp-xl.png',
        price: 40000,
        story: 'По словам Бутча Вига, Vox AC30 использовался на альбоме Nirvana Nevermind: "У Курта был Mesa/Boogie, но мы также часто использовали Fender Bassman и Vox AC30 на Nevermind", - вспоминает Виг. "Я предпочитаю, чтобы усилитель звучал искаженно, а не использовал специальные эффекты или педали',
        more: '<a href="https://web.archive.org/web/20171012094041/https://www.guitarworld.com/archive-definitive-kurt-cobain-gear-guide">Ссылка на источник</a>',
    },
    {
        id: 'el21',
        category_mus: 'guitar',
        category_man: 'john-frusciante',
        name: '1961 Fender Stratocaster',
        img: 'img/man-john-frusciante/1961-fender-stratocaster-xl.png',
        price: 100000,
        story: 'Из интервью, найденного в Vintage Guitar, Джон Фрушанте говорит, что его красный Fender Stratocaster 1961 года выпуска - его третий любимый Strat.',
        more: '<img src="img/man-john-frusciante/john_guitar.jpg" alt="">',
    },
    {
        id: 'el22',
        category_mus: 'accessory',
        category_man: 'john-frusciante',
        name: 'Dunlop Tortex Standard 0.60mm Guitar Picks (50 шт.)',
        img: 'img/man-john-frusciante/dunlop-tortex-standard-0-60mm-guitar-picks-xl.png',
        price: 2000,
        story: 'На этой фотографии Джон Фрушанте поет в микрофон, его медиатор Dunlop Tortex 0.60 мм можно увидеть в держателе микрофонной стойки. Это кадр из записи выступления Red Hot Chili Peppers Live at Slane Castle (записано 23 августа 2003 года на территории замка Слэйн).',
        more: '<img src="img/man-john-frusciante/john_pick.jpg" alt="">',
    },
    {
        id: 'el23',
        category_mus: 'pedal',
        category_man: 'john-frusciante',
        name: 'MXR M102 Dyna Comp',
        img: 'img/man-john-frusciante/mxr-m102-dyna-comp-xl.png',
        price: 11500,
        story: 'Использованный в Blood Sugar Sex Magik, Джон использовал Dyna Comp в соло "Mellowship Slinky in B Major" и для вступления "Under The Bridge", и если вы зайдете на YouTube и посмотрите "Джон Фрушанте записывает Mellowship slinky in B Major соло", вы можете увидеть это справа от него.',
        more: '<img src="img/man-john-frusciante/john_pedal.jpg" alt="">',
    },
    {
        id: 'el24',
        category_mus: 'pedal',
        category_man: 'robert-deleo',
        name: 'Electro-Harmonix Bass Micro Synth XO',
        img: 'img/man-robert-deleo/electro-harmonix-bass-microsynth-effects-pedal-xl.png',
        price: 16000,
        story: 'На слайде 12 Роберт упоминает свой басовый Electro-Harmonix Bass Micro Synth XO, он есть на его скромном педалборде.',
        more: '<a href="https://www.musicradar.com/news/rig-tour-stone-temple-pilots">Ссылка на источник</a>',
    },
    {
        id: 'el25',
        category_mus: 'bass',
        category_man: 'robert-deleo',
        name: 'Fender Precision Bass',
        img: 'img/man-robert-deleo/fender-precision-bass-duplicate-xl.png',
        price: 47000,
        story: 'ДеЛео заявляет: "Я использовал Fender Precision 1965 года выпуска на "Same on the Inside"".',
        more: '<a href="https://www.guitarworld.com/features/stone-temple-pilots-robert-deleo">Ссылка на источник</a>',
    },
    {
        id: 'el26',
        category_mus: 'studio',
        category_man: 'robert-deleo',
        name: 'Line 6 Bass POD xt Pro',
        img: 'img/man-robert-deleo/line-6-bass-pod-xt-pro-xl.png',
        price: 20000,
        story: 'В статье о басисте говорится, что ДеЛео использует Line 6 Bass Pod xt Pro.',
        more: '<a href="https://www.guitarworld.com/features/stone-temple-pilots-robert-deleo">Ссылка на источник</a>',
    },
    {
        id: 'el27',
        category_mus: 'bass',
        category_man: 'robert-deleo',
        name: 'Schecter Robert DeLeo Model-T Signature Bass',
        img: 'img/man-robert-deleo/schecter-robert-deleo-model-t-signature-bass-xl.png',
        price: 45000,
        story: 'В статье о басисте говорится, что ДеЛео использует фирменный бас Schecter Robert Deleo Model-T.',
        more: '<a href="https://www.guitarworld.com/features/stone-temple-pilots-robert-deleo">Ссылка на источник</a>',
    },
    {
        id: 'el28',
        category_mus: 'accessory',
        category_man: 'yuriy-kasparyan',
        name: 'DiMarzio DP100 Super Distortion Pickup',
        img: 'img/man-yuriy-kasparyan/dimarzio-dp100-super-distortion-pickup-xl.png',
        price: 8500,
        story: 'Юрий использовал этот тип звукоснимателей для всех своих гитар Yamaha SG',
        more: '<iframe src="https://www.youtube.com/embed/x0vWCoufA5Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el29',
        category_mus: 'guitar',
        category_man: 'yuriy-kasparyan',
        name: 'Gibson Les Paul Custom',
        img: 'img/man-yuriy-kasparyan/gibson-les-paul-custom-duplicate-xl.png',
        price: 70000,
        story: 'На снимке можно увидеть Юрия, играющего на красной гитаре Gibson Les Paul.',
        more: '<img src="img/man-yuriy-kasparyan/yuriy_guitar.jpg" alt="">',
    },
    {
        id: 'el30',
        category_mus: 'pedal',
        category_man: 'flea',
        name: 'Boss ODB-3 Bass OverDrive',
        img: 'img/man-flea/boss-odb-3-bass-overdrive-xl.png',
        price: 12000,
        story: 'На фотографии педалборда Flea видно, что в какой-то момент он использовал педаль Boss ODB-3 Bass OverDrive. Более свежие фотографии и видео его настройки педали показывают, что эта педаль больше не используется им на концертах.',
        more: '<img src="img/man-flea/flea_pedal.jpg" alt="">',
    },
    {
        id: 'el31',
        category_mus: 'pedal',
        category_man: 'flea',
        name: 'Electro-Harmonix Original Q-Tron',
        img: 'img/man-flea/electro-harmonix-original-q-tron-xl.png',
        price: 14000,
        story: 'Примерно на 6:00 в видео звукоинженер Flea показывает педаль Electro Harmonix Q Tron, использованную в педалборде Flea во время тура Im With You.',
        more: '<iframe src="https://www.youtube.com/embed/3ARZGwfhC_U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el32',
        category_mus: 'bass',
        category_man: 'flea',
        name: 'Ernie Ball Music Man Stingray Bass',
        img: 'img/man-flea/ernie-ball-music-man-stingray-bass-xl.png',
        price: 90000,
        story: 'Один из главных басов Фли на протяжении всей его карьеры. Можно увидеть в таких музыкальных клипах, как "Aeroplane" и "Coffee Shop". Этот бас используется в обучающем видео Чеда Смита "Red Hot Rhythm Meth".',
        more: '<img src="img/man-flea/flea_bass.jpg" alt="">',
    },
    {
        id: 'el33',
        category_mus: 'bass',
        category_man: 'flea',
        name: 'Wal Mk II Bass',
        img: 'img/man-flea/wal-mk-ii-bass-xl.png',
        price: 80000,
        story: 'Фли использовал синюю модель этого баса в студии во время записи альбома "Blood Sugar Sex Magic". Он использовал этот бас во всех песнях, кроме "Funky Monks" и "The Righteous and the Wicked" (в них он использовал 5-струнный musicman stingray).',
        more: '<iframe src="https://www.youtube.com/embed/z0tTJ4SakE0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el34',
        category_mus: 'piano',
        category_man: 'alan-wilder',
        name: 'Akai MX-1000',
        img: 'img/man-alan-wilder/akai-mx-1000-xl.png',
        price: 20000,
        story: 'На 2:05 на видео мужно увидеть Алана, использующего Akai MX-1000. Он использовал Akai во время devotional и exotic туров 1993/94, он использовал его в качестве дополнительного инструмента, когда ему нужно было больше клавиш',
        more: '<iframe src="https://www.youtube.com/embed/TSYU1O0sqSI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el35',
        category_mus: 'studio',
        category_man: 'alan-wilder',
        name: 'Dynaudio M2',
        img: 'img/man-alan-wilder/dynaudio-m2-xl.png',
        price: 50000,
        story: 'Комментарий Алана Уайлдера после продажи студии относительно его давнего выбора мониторов Dynaudio M2: "Я большой поклонник Dynaudio, годами не пользовался ничем другим. Надежная, точная и правильная, чрезвычайно приятна для прослушивания."',
        more: '<a href="http://auction.recoil.co.uk/dynaudio-m2-monitors/">Ссылка на источник</a>',
    },
    {
        id: 'el36',
        category_mus: 'piano',
        category_man: 'alan-wilder',
        name: 'Yamaha DX7-IID',
        img: 'img/man-alan-wilder/yamaha-dx7-iid-xl.png',
        price: 35000,
        story: 'Алан Уайлдер играл на Yamaha DX7 IID во время тура "Music for the Masses".',
        more: '<a href="https://www.depmode.com/Depeche_Mode_Music_For_The_Masses_Tour.php">Ссылка на источник</a>',
    },
    {
        id: 'el37',
        category_mus: 'studio',
        category_man: 'alan-wilder',
        name: 'Yamaha SPX90 II Digital Multi-Effects Processor',
        img: 'img/man-alan-wilder/yamaha-spx90-digital-multi-effects-processor-xl.png',
        price: 27000,
        story: '20-е место в списке оборудования Алана Уайлдера',
        more: '<a href="https://www.soundonsound.com/sos-past-articles-back-january-1994-now-online">Ссылка на источник</a>',
    },
    {
        id: 'el38',
        category_mus: 'pedal',
        category_man: 'dean-deleo',
        name: 'Boss CE-2W Chorus Waza Craft',
        img: 'img/man-dean-deleo/boss-ce-2w-chorus-xl.png',
        price: 22000,
        story: 'На 8 слайде статьи Дин рассказывает о том, как он перестал полагаться на хорус и изменил звучание хоруса, чтобы оно больше походило на звучание "2-й гитары" Алесли. Он обсуждает возможность снятия с производства своего Roland CE-1 и замены его на Waza Craft, а CE-2W изображен на его педалборде.',
        more: '<a href="https://www.musicradar.com/news/rig-tour-stone-temple-pilots">Ссылка на источник</a>',
    },
    {
        id: 'el39',
        category_mus: 'guitar',
        category_man: 'dean-deleo',
        name: 'Gibson Les Paul Special',
        img: 'img/man-dean-deleo/gibson-les-paul-special-xl.png',
        price: 95000,
        story: 'На снимке можно увидеть, что ДеЛео держит в руках Gibson Les Paul Special',
        more: '<img src="img/man-dean-deleo/dean_guitar.jpg" alt="">',
    },
    {
        id: 'el40',
        category_mus: 'guitar',
        category_man: 'dean-deleo',
        name: 'Gibson Les Paul Standard Electric Guitar',
        img: 'img/man-dean-deleo/gibson-les-paul-standard-electric-guitar-xl.png',
        price: 105000,
        story: 'На диаграмме оборудования для тура Army of Anyone, опубликованной в журнале Guitar magazine, вы можно увидеть, что Дин путешествовал со своими двумя Gibson Les Paul Standard Electric Guitar 70-х годов, которые он купил новыми, будучи подростком.',
        more: '<img src="img/man-dean-deleo/dean_guitar2.jpg" alt="">',
    },
    {
        id: 'el41',
        category_mus: 'amp',
        category_man: 'dean-deleo',
        name: 'Marshall Handwired 1958X',
        img: 'img/man-dean-deleo/marshall-handwired-1958x-xl.png',
        price: 65000,
        story: 'Архив Дина Гира: Когда журнал Guitar World спросил: "Я не слышу слишком много эффектов на записи", Дин ответил: "На самом деле их не было. На "John" и "Hello Hello" я использовал Marshall Handwired 1958X.',
        more: '<a href="https://www.belowempty.com/bandinfo.php?s=equipment&p=dean_deleo">Ссылка на источник</a>',
    },
    {
        id: 'el42',
        category_mus: 'amp',
        category_man: 'dean-deleo',
        name: 'Orange Overdrive OD120',
        img: 'img/man-dean-deleo/orange-overdrive-od120-xl.png',
        price: 40000,
        story: 'На 32:22 в кратком изложении Rick Beato Rig Рик рассказывает о том, как он получил свою оранжевую голову Overdrive после того, как увидел, как Дин использовал ее во время отслеживания записи.',
        more: '<iframe src="https://www.youtube.com/embed/L03IGkiMJjQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el43',
        category_mus: 'drums',
        category_man: 'dave-grohl',
        name: 'Aquarian Hi-Energy',
        img: 'img/man-dave-grohl/aquarian-hi-energy-xl.png',
        price: 3000,
        story: 'Дэйв Грол использовал Aquarian Hi-Energy head, потому что это был единственный бренд, который не ломался, когда он играл на нем.',
        more: '<a href="https://www.livenirvana.com/equipment/dave.php">Ссылка на источник</a>',
    },
    {
        id: 'el44',
        category_mus: 'accessory',
        category_man: 'dave-grohl',
        name: 'Aquarian Power-Sleeve 2B',
        img: 'img/man-dave-grohl/aquarian-power-sleeve-2b-xl.png',
        price: 1700,
        story: 'Дэйв Грол использовал палочки Aquarian Power-Sleeve 2B, находясь в Nirvana. Грол сказал, что он "держал их вверх ногами". На фотографии хорошо виден нейлоновый материал, содержащийся в палочках.',
        more: '<img src="img/man-dave-grohl/dave-stick.jpg" alt="">',
    },
    {
        id: 'el45',
        category_mus: 'guitar',
        category_man: 'dave-grohl',
        name: 'Gibson Trini Lopez Standard Custom Reissue Electric Guitar',
        img: 'img/man-dave-grohl/gibson-trini-lopez-standard-custom-reissue-electric-guitar-xl.png',
        price: 110000,
        story: '"Это чертовски хорошая гитара. Я видел это в гитарном магазине в Бетесде, штат Мэриленд. Я думаю, это был 1992 или 93-й или что-то в этом роде, я все еще был в Nirvana, когда купил ее."',
        more: '<iframe src="https://www.youtube.com/embed/PljU-A0MFsY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el46',
        category_mus: 'accessory',
        category_man: 'dave-grohl',
        name: 'Regal Tip 5B',
        img: 'img/man-dave-grohl/regal-tip-5b-xl.png',
        price: 1800,
        story: 'Дэйв Грол держал палочки Regal Tip 5B вверх ногами',
        more: '<a href="https://www.livenirvana.com/equipment/dave.php">Ссылка на источник</a>',
    },
    {
        id: 'el47',
        category_mus: 'drums',
        category_man: 'dave-grohl',
        name: 'Zildjian 18" A Medium Crash',
        img: 'img/man-dave-grohl/zildjian-18-a-medium-crash-xl.png',
        price: 22000,
        story: 'Дэйв использовал эти тарелки во время своего пребывания в Nirvana',
        more: '<a href="https://www.livenirvana.com/equipment/dave.php">Ссылка на источник</a>',
    },
    {
        id: 'el48',
        category_mus: 'pedal',
        category_man: 'viktor-tsoy',
        name: 'Boss OD-2 Turbo OverDrive',
        img: 'img/man-viktor-tsoy/boss-od-2-turbo-overdrive-guitar-effects-pedal-xl.png',
        price: 11000,
        story: 'В видео присутствует гитарный эффект Boss OD2. Юрий Каспарян использовал ту же педаль на концертах и записях',
        more: '<iframe src="https://www.youtube.com/embed/QaICglrHQdY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el49',
        category_mus: 'bass',
        category_man: 'viktor-tsoy',
        name: 'Fender Japanese 87" PJ-555 Jazz Bass Special',
        img: 'img/man-viktor-tsoy/fender-87-jazz-bass-special-japanese-pj-555-xl.png',
        price: 50000,
        story: 'Редкая фотография Виктора Цоя с японским басом Fender Japanese 87" PJ-555 Jazz Bass Special.',
        more: '<img src="img/man-viktor-tsoy/viktor_bass.jpg" alt="">',
    },
    {
        id: 'el50',
        category_mus: 'guitar',
        category_man: 'viktor-tsoy',
        name: 'Kramer Ferrington KFS-2',
        img: 'img/man-viktor-tsoy/kramer-ferrington-kft-2-xl.png',
        price: 38000,
        story: 'В этом клипе Виктор Цой играет на своем черном Kramer Ferrington',
        more: '<iframe src="https://www.youtube.com/embed/GNpy6PQJpXE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el51',
        category_mus: 'amp',
        category_man: 'mike-starr',
        name: 'Ampeg SVT-810E 8x10 Bass Cabinet',
        img: 'img/man-mike-starr/ampeg-svt-810e-8x10-bass-cabinet-xl.png',
        price: 45000,
        story: '"Я получил электронное письмо от Эвана Шили из bass northwest в Сиэтле, он работал с Alice In Chains над Facelift (1990) и Dirt (1992). Он говорит: "Я действительно работал с Майком Старром и Alice In Chains над их первыми двумя студийными альбомами. Тон, который вы слышите, был от баса Spector NS2, усилителя Ampeg SVT и процессора ART SGX Nightbass"',
        more: '<a href="http://www.leftybassist.com/viewtopic.php?f=6&t=3167">Ссылка на источник</a>',
    },
    {
        id: 'el52',
        category_mus: 'studio',
        category_man: 'mike-starr',
        name: 'ART SGX Nightbass',
        img: 'img/man-mike-starr/art-sgx-nightbass-xl.png',
        price: 12000,
        story: '"Я получил электронное письмо от Эвана Шили из bass northwest в Сиэтле, он работал с Alice In Chains над Facelift (1990) и Dirt (1992). Он говорит: "Я действительно работал с Майком Старром и Alice In Chains над их первыми двумя студийными альбомами. Тон, который вы слышите, был от баса Spector NS2, усилителя Ampeg SVT и процессора ART SGX Nightbass"',
        more: '<a href="http://www.leftybassist.com/viewtopic.php?f=6&t=3167">Ссылка на источник</a>',
    },
    {
        id: 'el53',
        category_mus: 'bass',
        category_man: 'mike-starr',
        name: 'Fender Jazz Bass Special',
        img: 'img/man-mike-starr/fender-jazz-bass-special-xl.png',
        price: 30000,
        story: 'Майк использовал этот бас в клипе We Die Young и на ранних концертах',
        more: '<img src="img/man-mike-starr/mike_bass.jpg" alt="">',
    },
    {
        id: 'el54',
        category_mus: 'bass',
        category_man: 'mike-starr',
        name: 'Rickenbacker 4001',
        img: 'img/man-mike-starr/rickenbacker-4001-xl.png',
        price: 60000,
        story: 'Басиста Майка Старра можно увидеть играющим на Rickenbacker 4001 в его оригинальной группе "Sato". Он обычно использовал этот бас во время концертов. Позже он стал известен тем, что играл на басах Spector NS-2 с Alice in Chains.',
        more: '<img src="img/man-mike-starr/mike_bass2.jpg" alt="">',
    },
    {
        id: 'el55',
        category_mus: 'studio',
        category_man: 'dave-gahan',
        name: 'BAE 1073 MP',
        img: 'img/man-dave-gahan/bae-1073-mp-xl.png',
        price: 70000,
        story: 'Интервьюер говорит: "Вокальные дорожки Дэйва Гаана записываются по цепочке, которая часто состоит из Shure SM7, проходящего через BAE 1073".',
        more: '<a href="https://sonicscoop.com/david-gahan-of-depeche-mode-an-inside-look-at-his-very-personal-studio//#sthash.LaQPYjqT.dpbs">Ссылка на источник</a>',
    },
    {
        id: 'el56',
        category_mus: 'studio',
        category_man: 'dave-gahan',
        name: 'Empirical Labs EL8X Distressor',
        img: 'img/man-dave-gahan/empirical-labs-el8x-distressor-xl.png',
        price: 50000,
        story: 'Можно заметить 2 Empirical Labs EL8X Distressor на столе Дэйва.',
        more: '<a href="https://sonicscoop.com/david-gahan-of-depeche-mode-an-inside-look-at-his-very-personal-studio//#sthash.LaQPYjqT.dpbs">Ссылка на источник</a>',
    },
    {
        id: 'el57',
        category_mus: 'studio',
        category_man: 'dave-gahan',
        name: 'LaChapell 992EG Tube Mic Pre',
        img: 'img/man-dave-gahan/lachapell-992eg-tube-mic-pre-xl.png',
        price: 55000,
        story: 'Курт Уэнала, техник Дэйва Гаана, говорит: “LaChapell с SM7 прекрасен. Он звучит очень тепло, как будто на нем уже установлен компрессор. Он очень маслянистый.',
        more: '<a href="https://sonicscoop.com/david-gahan-of-depeche-mode-an-inside-look-at-his-very-personal-studio//#sthash.LaQPYjqT.dpbs">Ссылка на источник</a>',
    },
    {
        id: 'el58',
        category_mus: 'microphon',
        category_man: 'dave-gahan',
        name: 'Shure SM7B',
        img: 'img/man-dave-gahan/shure-sm7b-vocal-dynamic-microphone-xl.png',
        price: 38000,
        story: 'В статье, подробно описывающей личное пространство студии Дэйва Гаана в Нью-Йорке и запись альбома Delta Machine, инженер и продюсер Курт Уэнала рассказывает, что он записывает вокальные треки Дэйва Гаана с помощью Shure SM7, проходящего через BAE 1073.',
        more: '<a href="https://sonicscoop.com/david-gahan-of-depeche-mode-an-inside-look-at-his-very-personal-studio//#sthash.LaQPYjqT.dpbs">Ссылка на источник</a>',
    },
    {
        id: 'el59',
        category_mus: 'microphon',
        category_man: 'martin-gore',
        name: 'Beyerdynamic TG V70d',
        img: 'img/man-martin-gore/beyerdynamic-tg-v70d-xl.png',
        price: 35000,
        story: 'Согласно веб-сайту Beyerdynamic: "Дэйв Гаан и гитарист Мартин Гор оба используют портативные передатчики TG 1000 со сменными капсулами hypercardioid TG V70d для своих вокальных партий".',
        more: '<a href="https://europe.beyerdynamic.com/company/press/depeche-mode-with-beyerdynamic-at-the-world-tour">Ссылка на источник</a>',
    },
    {
        id: 'el60',
        category_mus: 'studio',
        category_man: 'martin-gore',
        name: 'Kemper Profiler Rack',
        img: 'img/man-martin-gore/kemper-profiler-rack-guitar-amp-system-xl.png',
        price: 70000,
        story: 'Рассказывая о некоторых элементах настройки оборудования Мартина Гора для тура Depeche Mode 2013 Delta Machine, Джез Уэбб упоминает использование Мартином Гором усилителя Kemper Profiling (3:17 в видео).: "Новым дополнением к установке является Kemper Profiler Rack."',
        more: '<iframe src="https://www.youtube.com/embed/nEJexGS8vng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el61',
        category_mus: 'guitar',
        category_man: 'martin-gore',
        name: 'Knight Gretsch Double Anniversary Sunburst Electric Guitar',
        img: 'img/man-martin-gore/knight-gretsch-double-anniversary-sunburst-electric-guitar-xl.png',
        price: 40000,
        story: 'Звукоинженер Мартина Гора Джез Уэбб рассказывает о двойных юбилейных копиях Gretsch, которые Дик Найт сделал для Мартина: “Он сделал классическую версию green, а затем мы также сделали версию sunburst.',
        more: '<iframe src="https://www.youtube.com/embed/cCIxe97Eqbk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el62',
        category_mus: 'studio',
        category_man: 'martin-gore',
        name: 'MIDI Solutions T8 8-output MIDI Thru Box',
        img: 'img/man-martin-gore/midi-solutions-t8-8-output-midi-thru-box-xl.png',
        price: 16000,
        story: 'В видео представлены сценарии инструментов тура Depeche Mode Delta Machine, в том числе MIDI Solutions T8 8-output MIDI Through Box',
        more: '<iframe src="https://www.youtube.com/embed/nEJexGS8vng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el63',
        category_mus: 'piano',
        category_man: 'martin-gore',
        name: 'Moog One Polyphonic Analog Synthesizer',
        img: 'img/man-martin-gore/moog-one-polyphonic-analog-synthesizer-xl.png',
        price: 120000,
        story: 'В видео Мартин отвечает на вопросы и рассказывает о том, что он самый первый человек, у которого появился этот синтезатор.',
        more: '<iframe src="https://www.youtube.com/embed/W2-BX6QRD3Y" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el64',
        category_mus: 'drums',
        category_man: 'vinnie-paul',
        name: 'ddrum 14x8" Vinnie Paul Signature Snare',
        img: 'img/man-vinnie-paul/ddrum-14x8-vinnie-paul-signature-snare-xl.png',
        price: 28000,
        story: 'Это его фирменный малый барабан, который прилагался к его фирменному набору ddrum.',
        more: '<a href="https://www.ddrum.com/product?id=vpsd8x14drgnltd">Ссылка на источник</a>',
    },
    {
        id: 'el65',
        category_mus: 'drums',
        category_man: 'vinnie-paul',
        name: 'Pearl MRX Masters Drum Set',
        img: 'img/man-vinnie-paul/pearl-mrx-masters-drum-set-xl.png',
        price: 85000,
        story: 'До того, как Винни начал играть на ddrum, он был фанатом Pearl',
        more: '<img src="img/man-vinnie-paul/vin_drum.jpg" alt="">',
    },
    {
        id: 'el66',
        category_mus: 'drums',
        category_man: 'vinnie-paul',
        name: 'Sabian 14" AA Rock Hats',
        img: 'img/man-vinnie-paul/sabian-14-aa-rock-hats-xl.png',
        price: 32000,
        story: 'Перечислены в статье об оборудовании Винни Пола.',
        more: '<a href="https://www.drummerworld.com/drummers/Vinnie_Paul.html">Ссылка на источник</a>',
    },
    {
        id: 'el67',
        category_mus: 'accessory',
        category_man: 'vinnie-paul',
        name: 'Vic Firth Vinnie Paul Signature (SVP) drum sticks',
        img: 'img/man-vinnie-paul/vic-firth-vinnie-paul-signature-svp-drum-sticks-xl.png',
        price: 2000,
        story: 'Фирменные барабанные палочки Винни Пола от Вика Ферта',
        more: '<img src="img/man-vinnie-paul/vin_stick.jpg" alt="">',
    },
    {
        id: 'el68',
        category_mus: 'studio',
        category_man: 'krist-novoselic',
        name: 'Ampeg SVT 400T',
        img: 'img/man-krist-novoselic/ampeg-svt-400t-xl.png',
        price: 70000,
        story: '"По-моему, SVT 400T появился в начале 1991 года. Он видел много дорог, и я почти уверен, что он использовал его для записи Nevermind.',
        more: '<img src="img/man-krist-novoselic/krist_studio.jpg" alt="">',
    },
    {
        id: 'el69',
        category_mus: 'bass',
        category_man: 'krist-novoselic',
        name: 'Epiphone Jack Casady Signature',
        img: 'img/man-krist-novoselic/epiphone-jack-casady-signature-xl.png',
        price: 45000,
        story: 'На фотографии Новоселича можно увидеть играющим на бас-гитаре Epiphone Jack Casady на выступлении с Полом Маккартни.',
        more: '<img src="img/man-krist-novoselic/krist_bass.jpg" alt="">',
    },
    {
        id: 'el70',
        category_mus: 'bass',
        category_man: 'krist-novoselic',
        name: 'Gibson Ripper Bass',
        img: 'img/man-krist-novoselic/gibson-ripper-bass-xl.png',
        price: 85000,
        story: '"У Криста было по крайней мере две штуки из черного дерева с натуральной отделкой. Один из Gibson Ripper Bass Криста можно увидеть в клипе Come As You Are;',
        more: '<iframe src="https://www.youtube.com/embed/vabnZ9-ex7o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el71',
        category_mus: 'bass',
        category_man: 'krist-novoselic',
        name: 'Gibson Thunderbird IV Bass',
        img: 'img/man-krist-novoselic/gibson-thunderbird-iv-bass-xl.png',
        price: 90000,
        story: '"Я переделал эбонитовый бас из черного в хромированный, и Крист в конце концов отдал его Мэтту Лукину из Mudhoney в 1994 году".',
        more: '<img src="img/man-krist-novoselic/krist_bass2.jpg" alt="">',
    },
    {
        id: 'el72',
        category_mus: 'pedal',
        category_man: 'krist-novoselic',
        name: 'Pro Co RAT 2',
        img: 'img/man-krist-novoselic/pro-co-rat-distortion-pedal-xl.png',
        price: 13000,
        story: 'Любимая педаль дисторшна Криста. Ее можно увидеть на его педалборде с выступления на MTV 1993 года',
        more: '<img src="img/man-krist-novoselic/krist_pedal.jpg" alt="">',
    },
    {
        id: 'el73',
        category_mus: 'drums',
        category_man: 'sean-kinney',
        name: 'Pearl 14x6.5 Free Floating Snare',
        img: 'img/man-sean-kinney/pearl-14x6-5-free-floating-snare-xl.png',
        price: 38000,
        story: 'На фотографии видно, как Шон Кинни в эпоху Facelift (1990) использует Pearl 14x6.5 Free Floating Snare.',
        more: '<img src="img/man-sean-kinney/sean_drum.jpg" alt="">',
    },
    {
        id: 'el74',
        category_mus: 'drums',
        category_man: 'sean-kinney',
        name: 'Remo Ambassador Hazy Snare Side Drumhead',
        img: 'img/man-sean-kinney/remo-ambassador-hazy-snare-side-drumhead-xl.png',
        price: 4000,
        story: 'В нижней части фотографии, если присмотреться повнимательнее, можно увидеть логотип Remo Сrown на малом барабане Шона.',
        more: '<img src="img/man-sean-kinney/sean_drum2.jpg" alt="">',
    },
    {
        id: 'el75',
        category_mus: 'drums',
        category_man: 'sean-kinney',
        name: 'Sabian 19" AA Rock Crash',
        img: 'img/man-sean-kinney/sabian-19-aa-rock-crash-xl.png',
        price: 15000,
        story: 'На фотографии Кинни сидит за ударной установкой с двумя тарелками Sabian.',
        more: '<img src="img/man-sean-kinney/sean_drum3.jpg" alt="">',
    },
    {
        id: 'el76',
        category_mus: 'piano',
        category_man: 'andy-fletcher',
        name: 'Access Virus TI Polar',
        img: 'img/man-andy-fletcher/access-virus-ti-polar-xl.png',
        price: 70000,
        story: 'Звукоинженер Depeche Mode во время их тура Delta Machine в 2013 году, рассказывает о некоторых клавишных и синтезаторах, используемых группой вживую на сцене. Начиная с 0:21, он рассказывает об Access Virus TI Polar Флетчера: "Итак, вот мы на левой стороне сцены, на месте Энди Флетчера."',
        more: '<iframe src="https://www.youtube.com/embed/nEJexGS8vng" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el77',
        category_mus: 'piano',
        category_man: 'andy-fletcher',
        name: 'E-mu Emax',
        img: 'img/man-andy-fletcher/e-mu-emax-xl.png',
        price: 55000,
        story: 'Энди Флетчер играл на E-mu Emax HD/SE и Yamaha DX7 IID во время тура "Music for the Masses".',
        more: '<a href="https://www.depmode.com/Depeche_Mode_Music_For_The_Masses_Tour.php">Ссылка на источник</a>',
    },
    {
        id: 'el78',
        category_mus: 'piano',
        category_man: 'andy-fletcher',
        name: 'Moog Prodigy',
        img: 'img/man-andy-fletcher/moog-prodigy-synthesizer-m.png',
        price: 95000,
        story: 'Первый синтезатор Флетча, который Винс Кларк убедил его купить за 295 фунтов стерлингов в июле 1980 года в музыкальном магазине HONKY-TONK в Хэдли, Эссекс. Эндрю Флетчер появляется с Moog Prodigy на британском телешоу "Top of the Pops" в 1981 году',
        more: '<a href="https://books.google.ru/books?id=8dlapcBLwu0C&hl=ru">Ссылка на источник</a>',
    },
    {
        id: 'el79',
        category_mus: 'studio',
        category_man: 'andy-fletcher',
        name: 'Muse Research Receptor 2',
        img: 'img/man-andy-fletcher/muse-research-receptor-2-xl.png',
        price: 28000,
        story: 'В интервью дорожной команде DM во время тура Delta Machine Пол Истман сказал MusicRadar: "Это установка Флетча Muse Research Receptor 2.',
        more: '<a href="https://www.musicradar.com/news/guitars/depeche-modes-live-setup-revealed-245774">Ссылка на источник</a>',
    },
    {
        id: 'el80',
        category_mus: 'piano',
        category_man: 'andy-fletcher',
        name: 'Roland SH-1',
        img: 'img/man-andy-fletcher/roland-sh-1-xl.png',
        price: 85000,
        story: 'На фото Флетчер явно держит Roland SH-1.',
        more: '<img src="img/man-andy-fletcher/andy_piano.jpg" alt="">',
    },
    {
        id: 'el81',
        category_mus: 'drums',
        category_man: 'eric-kretz',
        name: 'Ludwig Black Beauty 6.5 x 14 Snare Drum',
        img: 'img/man-eric-kretz/ludwig-black-beauty-6-5-x-14-snare-drum-xl.png',
        price: 40000,
        story: 'В статье Ludwig Black Beauty 6.5 x 14 Snare Drum значится в списке использованного Эриком оборудования',
        more: '<a href="https://drummagazine.com/eric-kretz-revving-up-the-stp-machine/">Ссылка на источник</a>',
    },
    {
        id: 'el82',
        category_mus: 'drums',
        category_man: 'eric-kretz',
        name: 'Tama Bell Brass Snare Drum 14" x6.5"',
        img: 'img/man-eric-kretz/tama-bell-brass-snare-drum-14-x6-5-xl.png',
        price: 22000,
        story: 'В статье в журнале Drum Magazine Эрик Крец упоминает об использовании латунного малого барабана Tama Bell, известного как "Терминатор", взятого напрокат у Drum Doctors для избранных песен на Core.',
        more: '<a href="https://drummagazine.com/eric-kretz-remembers-stone-temple-pilots-debut-album/">Ссылка на источник</a>',
    },
    {
        id: 'el83',
        category_mus: 'studio',
        category_man: 'scott-weiland',
        name: 'BAE 1073 Dual DMP Dual Channel Desktop Mic Pre',
        img: 'img/man-scott-weiland/bae-1073-dual-dmp-dual-channel-desktop-mic-pre-xl.png',
        price: 60000,
        story: '"Скотт Вейланд и продюсер Рик Паркер широко использовали BAE 1073 Dual DMP Dual Channel Desktop Mic Pre на последнем альбоме."',
        more: '<a href="https://www.baeaudio.com/">Ссылка на источник</a>',
    },
    {
        id: 'el84',
        category_mus: 'microphon',
        category_man: 'scott-weiland',
        name: 'Shure Beta 58A Vocal Microphone',
        img: 'img/man-scott-weiland/shure-beta-58a-vocal-microphone-xl.png',
        price: 5000,
        story: 'Скотт Вейланд: "Но вернемся к первоначальному вопросу: одной из первых вещей, которые у меня были, когда мы играли в маленьких клубах по всему Лос-Анджелесу и округу Ориндж, был SM58. Моим первым помощником был вокальный мастер Shure; я купил его на гаражной распродаже."',
        more: '<a href="https://www.belowempty.com/articles.php?s=story&id=40">Ссылка на источник</a>',
    },
    {
        id: 'el85',
        category_mus: 'microphon',
        category_man: 'scott-weiland',
        name: 'Shure SM7',
        img: 'img/man-scott-weiland/shure-sm7-xl.png',
        price: 13000,
        story: '"Весь вокал на Core, нашем первом альбоме, был записан с помощью SM7".',
        more: '<a href="https://www.belowempty.com/articles.php?s=story&id=40">Ссылка на источник</a>',
    },
    {
        id: 'el86',
        category_mus: 'microphon',
        category_man: 'scott-weiland',
        name: 'Shure SM58',
        img: 'img/man-scott-weiland/shure-sm58-xl.png',
        price: 3000,
        story: 'Согласно этому сайту, Вейланд заявил: "Одним из первых оборудований, которым я владел, когда мы играли в маленьких клубах по всему Лос-Анджелесу и округу Ориндж, был SM58".',
        more: '<a href="https://www.belowempty.com/bandinfo.php?s=equipment&p=scott_weiland#shuresm7">Ссылка на источник</a>',
    },
    {
        id: 'el87',
        category_mus: 'amp',
        category_man: 'phil-anselmo',
        name: 'Ampeg VT-22 Amplifier',
        img: 'img/man-phil-anselmo/ampeg-vt-22-amplifier-xl.png',
        price: 50000,
        story: 'Можно увидеть усилитель в эпизоде 3 Metal Grasshopper на 3:28',
        more: '<iframe src="https://www.youtube.com/embed/hbdHk1vlsPw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el88',
        category_mus: 'guitar',
        category_man: 'phil-anselmo',
        name: 'Fender Stratocaster Electric Guitar',
        img: 'img/man-phil-anselmo/fender-stratocaster-electric-guitar-xl.png',
        price: 33000,
        story: 'Фил играет на страте на видео',
        more: '<iframe src="https://www.youtube.com/embed/v2MIBVJeqpI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el89',
        category_mus: 'guitar',
        category_man: 'phil-anselmo',
        name: 'Ovation 1669 Custom Legend',
        img: 'img/man-phil-anselmo/ovation-1669-custom-legend-xl.png',
        price: 80000,
        story: 'Какая ваша основная гитара? Ансельмо: "SG, Джек, и Ovation 1669 Custom Legend; Я играю на акустике Ovation."',
        more: '<img src="img/man-phil-anselmo/phil_guitar.jpg" alt="">',
    },
    {
        id: 'el90',
        category_mus: 'drums',
        category_man: 'chad-smith',
        name: 'Pearl 14x6.5 Steel Sensitone Snare',
        img: 'img/man-chad-smith/pearl-14x6-5-steel-sensitone-snare-xl.png',
        price: 27000,
        story: 'Звукоинженер Чеда Смита Крис Уоррен рассказывает про Pearl 14x6.5 Steel Sensitone Snare на 0:52 в видео об оборудовании Чеда.',
        more: '<iframe src="https://www.youtube.com/embed/h1NMZkIZ1rc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el91',
        category_mus: 'drums',
        category_man: 'chad-smith',
        name: 'Sabian 14" X Celerator HiHats',
        img: 'img/man-chad-smith/sabian-14-x-celerator-hihats-xl.png',
        price: 24000,
        story: 'На 2:04 на видео с установкой барабанов Чеда Смита его техник показывает Sabian 14" X Celerator HiHats.',
        more: '<iframe src="https://www.youtube.com/embed/h1NMZkIZ1rc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el92',
        category_mus: 'drums',
        category_man: 'chad-smith',
        name: 'Sabian 21" rock Ride',
        img: 'img/man-chad-smith/sabian-21-rock-ride-xl.png',
        price: 24000,
        story: 'На 1:57 на видео звукоинженер Чеда Смита Крис Уоррен упоминает Sabian 21" rock Ride.',
        more: '<iframe src="https://www.youtube.com/embed/h1NMZkIZ1rc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el93',
        category_mus: 'pedal',
        category_man: 'rex-brown',
        name: 'Carl Martin Two Faze Phaser',
        img: 'img/man-rex-brown/carl-martin-two-faze-phaser-xl.png',
        price: 11000,
        story: 'На 2:08 можно увидеть, как Рекс использует педаль Two Faze',
        more: '<iframe src="https://www.youtube.com/embed/A-hVCMIMaCk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el94',
        category_mus: 'amp',
        category_man: 'rex-brown',
        name: 'Hartke Kilo Bass Amp',
        img: 'img/man-rex-brown/hartke-kilo-bass-amp-xl.png',
        price: 25000,
        story: 'Рекс Браун, басист Pantera, Down и Kill Devil Hill, перешел на Samson/Hartke products в 2013 году. Ларри Хартке прислал ему басовый усилитель Hartke Kilo, и с тех пор Рекс Браун использовал эту голову на каждом выступлении.',
        more: '<img src="img/man-rex-brown/rex_amp.jpg" alt="">',
    },
    {
        id: 'el95',
        category_mus: 'bass',
        category_man: 'rex-brown',
        name: 'Jackson JS3 Concert Bass',
        img: 'img/man-rex-brown/jackson-js3-concert-bass-xl.png',
        price: 25000,
        story: 'Этот бас использовался Брауном при записи альбома Cowboys From Hell (1990)',
        more: '<iframe src="https://www.youtube.com/embed/eHjsHNqlMVc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el96',
        category_mus: 'pedal',
        category_man: 'rex-brown',
        name: 'MXR M-181 Bass Blowtorch',
        img: 'img/man-rex-brown/mxr-m-181-bass-blowtorch-xl.png',
        price: 10000,
        story: 'На фотографии педалборда Pantera, Kill Devil Hill и басиста Down Рекса Брауна, в левом верхнем углу педалборда Рекса Брауна находится MXR M-181 Bass Blowtorch.',
        more: '<img src="img/man-rex-brown/rex_pedal.jpg" alt="">',
    },
    {
        id: 'el97',
        category_mus: 'microphon',
        category_man: 'anthony-kiedis',
        name: 'Audix OM7 Dynamic Vocal Microphone',
        img: 'img/man-anthony-kiedis/audix-om7-dynamic-vocal-microphone-xl.png',
        price: 15000,
        story: 'Инженер Дэйв Рэт говорит: "Цепочка Энтони начинается с Audix OM7 Dynamic Vocal Microphone для всех вокалов, которые Рэт выбирал в течение нескольких лет."',
        more: '<a href="https://www.mixonline.com/live-sound/tour-profile-red-hot-chili-peppers-367922">Ссылка на источник</a>',
    },
    {
        id: 'el98',
        category_mus: 'pedal',
        category_man: 'anthony-kiedis',
        name: 'Electro-Harmonix V256',
        img: 'img/man-anthony-kiedis/electro-harmonix-v256-xl.png',
        price: 16000,
        story: 'Звук проходящий через педаль можно услыштать с 1:45 и 2:10 на видео.',
        more: '<iframe src="https://www.youtube.com/embed/kgmU7KMw7dw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
    },
    {
        id: 'el99',
        category_mus: 'guitar',
        category_man: 'anthony-kiedis',
        name: 'Martin 0-15',
        img: 'img/man-anthony-kiedis/martin-0-15-xl.png',
        price: 130000,
        story: 'Кидис играет на этой гитаре на AOL Session',
        more: '<img src="img/man-anthony-kiedis/anthony_guitar.jpg" alt="">',
    },
    {
        id: 'el100',
        category_mus: 'microphon',
        category_man: 'anthony-kiedis',
        name: 'Shure SM57 Dynamic Instrument Microphone',
        img: 'img/man-anthony-kiedis/shure-sm57-dynamic-instrument-microphone-xl.png',
        price: 6000,
        story: '"Энтони всегда использовал SM57 для своего ведущего вокала. Мы поставили его на подставку, но я уверен, что он держал его в руке. Вот как он получает свой звук."',
        more: '<a href="https://www.soundonsound.com/sos-past-articles-back-january-1994-now-online">Ссылка на источник</a>',
    },
];